language: d
os:
  - linux
  - osx

before_install:
    - sudo apt-get install cmake libsfml-dev

install:
  - git clone https://github.com/Jebbs/DSFMLC.git
  - cd DSFMLC
  - cmake .
  - sudo make install
